
# Taps
tap "caskroom/cask"
tap "caskroom/fonts"
tap "drakew/corgi"

# Binaries
brew "bash-completion"
brew "bat"
brew "exa"
brew "expect"
brew "corgi"
brew "ssh-copy-id"
brew "git-lfs"
brew "git-secret"
brew "the_silver_searcher"
brew "asdf"


# Apps
cask "iterm2"
cask "alfred"
cask "cakebrew"
cask "visual-studio-code"
cask "spectacle"
cask "insomnia"
cask "spectacle"
cask "font-hack"
cask "vagrant"
cask "appcleaner"
cask "cheatsheet"
cask "google-chrome"
cask "slack"